### ISSUE TITLE
SyntaxError in kernelbase.py

### ISSUE THREAD

**Issue by UserBoi1** [KWARC/GLIF#2]
A SyntaxError in ~/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py line 318 was causing the GLIF kernel to fail to run anything.
The SyntaxError was caused by the unnecessary provision of the argument ```channel='shell'``` in a call to ```set_parent()```, which was already accounted for by the use of the default argument ```channel='shell'``` in the definition of ```set_parent()```.
Removing the unnecessary argument solved the problem for me.

**Comment by jfschaefer** [comment]
Thanks for pointing that out! It appears that recent changes to ipykernel caused this problem. I've pushed a fix.
